name: "Build and publish all variant"
permissions: write-all
on:
  workflow_dispatch:
    inputs:
      stages:
        type: choice
        description: Select from which stage to start
        options:
        - stage1
        - stage2
        - stage3
  schedule:
    - cron: "0 0 * * 0"
env:
  GH_TOKEN: ${{ secrets.GH_PAT }}
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          for a in xubuntu-core kde-plasma-desktop cinnamon ubuntu-mate-core lubuntu-desktop
            do
              gh workflow run ${{ inputs.stages }}.yml -f variant=$a
          done
