name: "Build and publish all variant"
permissions: write-all
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          for a in xubuntu-core kde-plasma-desktop cinnamon ubuntu-mate-core lubuntu-desktop
            do
              gh workflow run docker-publish.yml -f variant=$a
          done
