name: "Build and publish - Stage 2"
on:
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Select variant
        options:
        - xubuntu-core
        - kde-plasma-desktop
        - cinnamon
        - ubuntu-mate-core
        - lubuntu-desktop
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: msh128/ubuntu-docker-base
  GH_TOKEN: ${{ secrets.GH_PAT }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout runner repository
        uses: actions/checkout@v4.1.1
      - name: Checkout Docker source repository
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{ env.IMAGE_NAME }}
          token: ${{ env.GH_TOKEN }}
          path: ${{ env.IMAGE_NAME }}
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.4.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Cache Docker layers
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-stage2-${{ inputs.variant }}
          restore-keys: |
            ${{ runner.os }}-buildx-stage2-
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Modify Dockerfile to match requested variant
        run: sed -i "s/ubuntu-docker-desktop:variant/ubuntu-docker-desktop:${{ inputs.variant }}/g" ${{ env.IMAGE_NAME }}/Dockerfile
      - name: Build and push ${{ inputs.variant }}
        id: build-and-push
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./${{ env.IMAGE_NAME }}
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.variant }}
          build-args: VARIANT=${{ inputs.variant }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Trigger next stage build
        run: gh workflow run stage3.yml -f variant=${{ inputs.variant }}
