name: "Build and publish - Stage 1"
on:
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Select variant
        options:
        - xubuntu-core
        - kde-plasma-desktop
        - cinnamon
        - ubuntu-mate-core
        - lubuntu-desktop
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: msh128/ubuntu-docker-desktop
  GH_TOKEN: ${{ secrets.GH_PAT }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout runner repository
        uses: actions/checkout@v4.1.1
      - name: Checkout Docker source repository
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{ env.IMAGE_NAME }}
          token: ${{ env.GH_TOKEN }}
          path: ${{ env.IMAGE_NAME }}
      - name: Initial checks
        id: check
        shell: bash
        run: |
          case ${{ inputs.variant }} in
            xubuntu-core)
              export STAGE1_LAST_BUILD=${{ vars.STAGE1_LAST_BUILD_XUBUNTU_CORE }}
              export STAGE1_DOCKERFILE_LAST_HASH=${{ vars.STAGE1_DOCKERFILE_LAST_HASH_XUBUNTU_CORE }}
              ;;
            kde-plasma-desktop)
              export STAGE1_LAST_BUILD=${{ vars.STAGE1_LAST_BUILD_KDE_PLASMA_DESKTOP }}
              export STAGE1_DOCKERFILE_LAST_HASH=${{ vars.STAGE1_DOCKERFILE_LAST_HASH_KDE_PLASMA_DESKTOP }}
              ;;
            cinnamon)
              export STAGE1_LAST_BUILD=${{ vars.STAGE1_LAST_BUILD_CINNAMON }}
              export STAGE1_DOCKERFILE_LAST_HASH=${{ vars.STAGE1_DOCKERFILE_LAST_HASH_CINNAMON }}
              ;;
            ubuntu-mate-core)
              export STAGE1_LAST_BUILD=${{ vars.STAGE1_LAST_BUILD_UBUNTU_MATE_CORE }}
              export STAGE1_DOCKERFILE_LAST_HASH=${{ vars.STAGE1_DOCKERFILE_LAST_HASH_UBUNTU_MATE_CORE }}
              ;;
            lubuntu-desktop)
              export STAGE1_LAST_BUILD=${{ vars.STAGE1_LAST_BUILD_LUBUNTU_DESKTOP }}
              export STAGE1_DOCKERFILE_LAST_HASH=${{ vars.STAGE1_DOCKERFILE_LAST_HASH_LUBUNTU_DESKTOP }}
              ;;
          esac
          echo "STAGE1_LAST_BUILD=$STAGE1_LAST_BUILD" >> $GITHUB_ENV
          echo "STAGE1_DOCKERFILE_LAST_HASH=$STAGE1_DOCKERFILE_LAST_HASH" >> $GITHUB_ENV
          [ "$((($(date +%s)-$(date +%s --date $STAGE1_LAST_BUILD))/(3600*24)))" -gt 30 ] && echo "::set-output name=rebuild::true" || echo "::set-output name=rebuild::false"
          [ "$(md5sum ${{ env.IMAGE_NAME }}/Dockerfile)" != $STAGE1_DOCKERFILE_LAST_HASH ] && echo "::set-output name=rebuild::true" || echo "::set-output name=rebuild::false"
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.4.0
        if: ${{ steps.check.outputs.rebuild == 'true' && github.event_name != 'pull_request' }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
        if: ${{ steps.check.outputs.rebuild == 'true' }}
      - name: Cache Docker layers
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-stage1-${{ inputs.variant }}
          restore-keys: |
            ${{ runner.os }}-buildx-stage1-
        if: ${{ steps.check.outputs.rebuild == 'true' }}
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}
        if: ${{ steps.check.outputs.rebuild == 'true' && github.event_name != 'pull_request' }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        if: ${{ steps.check.outputs.rebuild == 'true' }}
      - name: Build and push ${{ inputs.variant }}
        id: build-and-push
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./${{ env.IMAGE_NAME }}
          push: true
          platforms: linux/amd64
          provenance: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.variant }}
          build-args: VARIANT=${{ inputs.variant }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        if: ${{ steps.check.outputs.rebuild == 'true' }}
      - name: Sign the published Docker image
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
        if: ${{ steps.check.outputs.rebuild == 'true' && github.event_name != 'pull_request' }}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        if: ${{ steps.check.outputs.rebuild == 'true' }}
      - name: Update repo variables
        shell: bash
        run: |
          case ${{ inputs.variant }} in
            xubuntu-core)
              gh variable set STAGE1_LAST_BUILD_XUBUNTU_CORE --body "$(date +%Y-%m-%d)"
              gh variable set STAGE1_DOCKERFILE_LAST_HASH_XUBUNTU_CORE --body "$(md5sum ${{ env.IMAGE_NAME }}/Dockerfile)"
              ;;
            kde-plasma-desktop)
              gh variable set STAGE1_LAST_BUILD_KDE_PLASMA_DESKTOP --body "$(date +%Y-%m-%d)"
              gh variable set STAGE1_DOCKERFILE_LAST_HASH_KDE_PLASMA_DESKTOP --body "$(md5sum ${{ env.IMAGE_NAME }}/Dockerfile)"
              ;;
            cinnamon)
              gh variable set STAGE1_LAST_BUILD_CINNAMON --body "$(date +%Y-%m-%d)"
              gh variable set STAGE1_DOCKERFILE_LAST_HASH_CINNAMON --body "$(md5sum ${{ env.IMAGE_NAME }}/Dockerfile)"
              ;;
            ubuntu-mate-core)
              gh variable set STAGE1_LAST_BUILD_UBUNTU_MATE_CORE --body "$(date +%Y-%m-%d)"
              gh variable set STAGE1_DOCKERFILE_LAST_HASH_UBUNTU_MATE_CORE --body "$(md5sum ${{ env.IMAGE_NAME }}/Dockerfile)"
              ;;
            lubuntu-desktop)
              gh variable set STAGE1_LAST_BUILD_LUBUNTU_DESKTOP --body "$(date +%Y-%m-%d)"
              gh variable set STAGE1_DOCKERFILE_LAST_HASH_LUBUNTU_DESKTOP --body "$(md5sum ${{ env.IMAGE_NAME }}/Dockerfile)"
              ;;
          esac
        if: ${{ steps.check.outputs.rebuild == 'true' }}
      - name: Trigger next stage build
        run: gh workflow run stage2.yml -f variant=${{ inputs.variant }}
